name: Hermes Agent

on:
  workflow_dispatch:

jobs:
  hermes:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Install Hermes
        run: |
          curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash
          echo "$HOME/.hermes/bin" >> $GITHUB_PATH

      - name: Check Hermes
        run: |
          hermes --help

      - name: Test outbound SSH to tmate server
        run: |
          timeout 15 nc -zv -w 10 nyc1.tmate.io 22 || echo "CONNECTION FAILED to nyc1.tmate.io:22"
          timeout 15 nc -zv -w 10 sfo2.tmate.io 22 || echo "CONNECTION FAILED to sfo2.tmate.io:22"

      - name: SSH into Runner
        uses: mxschmitt/action-tmate@v3
        with:
          connect-timeout-seconds: 30
