name: Hermes Agent

on:
  workflow_dispatch:

jobs:
  hermes:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Install Hermes
        run: |
          curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash
          echo "$HOME/.hermes/bin" >> $GITHUB_PATH

      - name: Check Hermes
        run: |
          hermes --help

      - name: SSH into Runner
        uses: mxschmitt/action-tmate@v3
