name: SSH Debug Session

on:
  workflow_dispatch:   # اجرای دستی از تب Actions

jobs:
  ssh-session:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true   # فقط خودت (بر اساس اکانت گیت‌هابت) وصل شی
        timeout-minutes: 180             # مدت زمانی که رانر زنده می‌مونه
