name: SSH

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check tmate
        run: |
          which tmate
          tmate -V

      - name: Start SSH
        uses: mxschmitt/action-tmate@v3.24
        with:
          install-dependencies: false
          limit-access-to-actor: true
